export const DEFAULT_SQLITE_PATH = "data/redactions.sqlite";

export const MEMORY_SQLITE_PATH = ":memory:";

export const DOCUMENT_AUDIT_ACTIONS = {
  REDACTED: "DOCUMENT_REDACTED",
  READ: "DOCUMENT_READ",
  REDACTIONS_READ: "DOCUMENT_REDACTIONS_READ",
  SEARCHED: "DOCUMENT_SEARCHED",
  UNREDACTED: "DOCUMENT_UNREDACTED",
  UNREDACTION_FAILED: "DOCUMENT_UNREDACTION_FAILED",
} as const;
